-- Moving Textures (WaterBoxes)
--   Every movtext type is set to 1 (normal water texture)
--   If you want to configure and setup other water type, change the value here
movtexqc_register('bbh_1_Movtex_0', 4, 1, 0)
movtexqc_register('ssl_1_Movtex_0', 8, 1, 0)
movtexqc_register('sl_1_Movtex_0', 10, 1, 0)
movtexqc_register('jrb_1_Movtex_0', 12, 1, 0)
movtexqc_register('castle_grounds_1_Movtex_0', 16, 1, 0)
movtexqc_register('sa_1_Movtex_0', 20, 1, 0)
movtexqc_register('bits_1_Movtex_0', 21, 1, 0)
movtexqc_register('bits_1_Movtex_1', 21, 1, 0)
movtexqc_register('lll_1_Movtex_0', 22, 1, 0)
movtexqc_register('ending_1_Movtex_0', 25, 1, 0)
movtexqc_register('castle_courtyard_1_Movtex_0', 26, 1, 0)
movtexqc_register('cotmc_1_Movtex_0', 28, 1, 0)

-- Scroll Textures
--   Uncomment and replace <id>, <offset> and <count> with the proper values
--   if you want to have scroll textures in your mod.
--[[
add_scroll_target(<id>, "VB_bbh_1_0xe02c320", <offset>, <count>)
add_scroll_target(<id>, "VB_bbh_1_0xe06d670", <offset>, <count>)
add_scroll_target(<id>, "VB_hmc_1_0xe02f8c0", <offset>, <count>)
add_scroll_target(<id>, "VB_hmc_1_0xe033440", <offset>, <count>)
add_scroll_target(<id>, "VB_hmc_1_0xe033740", <offset>, <count>)
add_scroll_target(<id>, "VB_hmc_1_0xe0393f0", <offset>, <count>)
add_scroll_target(<id>, "VB_ssl_1_0xe0239c0", <offset>, <count>)
add_scroll_target(<id>, "VB_ssl_1_0xe03d210", <offset>, <count>)
add_scroll_target(<id>, "VB_ssl_1_0xe03df40", <offset>, <count>)
add_scroll_target(<id>, "VB_ssl_1_0xe03e060", <offset>, <count>)
add_scroll_target(<id>, "VB_bob_1_0xe02cb30", <offset>, <count>)
add_scroll_target(<id>, "VB_bob_1_0xe02cce0", <offset>, <count>)
add_scroll_target(<id>, "VB_thi_1_0xe01c4d0", <offset>, <count>)
add_scroll_target(<id>, "VB_ttc_1_0xe013440", <offset>, <count>)
add_scroll_target(<id>, "VB_castle_grounds_1_0xe030580", <offset>, <count>)
add_scroll_target(<id>, "VB_castle_grounds_1_0xe03ad10", <offset>, <count>)
add_scroll_target(<id>, "VB_castle_grounds_1_0xe03c5a0", <offset>, <count>)
add_scroll_target(<id>, "VB_castle_grounds_1_0xe042dc0", <offset>, <count>)
add_scroll_target(<id>, "VB_bitdw_1_0xe020b60", <offset>, <count>)
add_scroll_target(<id>, "VB_vcutm_1_0xe021e80", <offset>, <count>)
add_scroll_target(<id>, "VB_bitfs_1_0xe010c20", <offset>, <count>)
add_scroll_target(<id>, "VB_bitfs_1_0xe0123d0", <offset>, <count>)
add_scroll_target(<id>, "VB_sa_1_0xe0427c0", <offset>, <count>)
add_scroll_target(<id>, "VB_sa_1_0xe045a40", <offset>, <count>)
add_scroll_target(<id>, "VB_bits_1_0xe034ed0", <offset>, <count>)
add_scroll_target(<id>, "VB_bits_1_0xe043590", <offset>, <count>)
add_scroll_target(<id>, "VB_bits_1_0xe043a50", <offset>, <count>)
add_scroll_target(<id>, "VB_bits_1_0xe043c10", <offset>, <count>)
add_scroll_target(<id>, "VB_bits_1_0xe045da0", <offset>, <count>)
add_scroll_target(<id>, "VB_lll_1_0xe043d60", <offset>, <count>)
add_scroll_target(<id>, "VB_lll_1_0xe044160", <offset>, <count>)
add_scroll_target(<id>, "VB_lll_1_0xe044220", <offset>, <count>)
add_scroll_target(<id>, "VB_ddd_1_0xe011010", <offset>, <count>)
add_scroll_target(<id>, "VB_ddd_1_0xe05eb60", <offset>, <count>)
add_scroll_target(<id>, "VB_ddd_1_0xe0617e0", <offset>, <count>)
add_scroll_target(<id>, "VB_wf_1_0xe0232f0", <offset>, <count>)
add_scroll_target(<id>, "VB_wf_1_0xe0392f0", <offset>, <count>)
add_scroll_target(<id>, "VB_ending_1_0xe01b2a0", <offset>, <count>)
add_scroll_target(<id>, "VB_castle_courtyard_1_0xe0435b0", <offset>, <count>)
add_scroll_target(<id>, "VB_pss_1_0xe021420", <offset>, <count>)
add_scroll_target(<id>, "VB_totwc_1_0xe0268e0", <offset>, <count>)
add_scroll_target(<id>, "VB_totwc_1_0xe0361c0", <offset>, <count>)
add_scroll_target(<id>, "VB_bowser_2_1_0xe006810", <offset>, <count>)
add_scroll_target(<id>, "VB_bowser_2_1_0xe00e510", <offset>, <count>)
add_scroll_target(<id>, "VB_ttm_1_0xe02b5f0", <offset>, <count>)
--]]
